name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - uses: actions/checkout@v2

      - name: Find schema
        run: cat schema.sql
      
      - name: Read schema
        run: psql -h postgres -d postgres_db -U postgres_user -f schema.sql
        env:
          PGPASSWORD: postgres_password

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install pip
        run: python -m ensurepip --upgrade

      - name: Install Poetry
        #run: pip install poetry
        #run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: poetry install
      - name: Create env.test file
        run: |
          touch .env.test
          echo DATABASE_URL=postgresql:///postgres_db >> .env.test
          echo SECRET_KEY=cd658d476cc15a67f687760f2de8b767 >> .env.test
          cat .env.test

      - name: Run tests
#        env:
#          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
#          HD_SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: poetry run coverage run --branch -m pytest --ignore=src/tests/repositories
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
#     - name: Run robot tests
#       run: bash run_robot_tests.sh
