name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - uses: actions/checkout@v2

      - name: Find schema
        run: cat schema.sql
      
      - name: Read schema
        run: psql -h postgres -d postgres_db -U postgres_user -f schema.sql
        env:
          PGPASSWORD: postgres_password

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install pip
        run: python -m ensurepip --upgrade

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/github/home/.local/bin:$PATH"

      - name: Install dependencies
        run: /github/home/.local/bin/poetry install
      
      - name: Create env.test file
        run: |
          touch .env.test
          echo DATABASE_URL=postgres://postgres_user:postgres_password@postgres:5432/postgres_db >> .env.test
          echo SECRET_KEY=cd658d476cc15a67f687760f2de8b767 >> .env.test
          cat .env.test

      - name: Run tests
        run: /github/home/.local/bin/poetry run coverage run --branch -m pytest 
      
      - name: Run pylint
        run: /github/home/.local/bin/poetry run pylint src/

      - name: Coverage report
        run: /github/home/.local/bin/poetry run coverage xml
      
      - name: Coverage report to Codecov
        run: |
          curl -s https://codecov.io/bash > .codecov
          chmod +x .codecov
          ./.codecov
      - name: Run robot tests
        run: bash run_robot_tests.sh postgres_db postgres_user
